/**
 * The bridge between the running game and the Agent layer
 * (docs/lv3/07-scheduler-plan.md §4.2/§13.5).
 *
 * This is the **only** module that knows both sides. `electron/agent/**` may not name an engine at
 * all — `tests/agent/boundary.test.ts` enforces that, and it is what keeps the agent layer free of
 * `WorldState` — while `electron/main.ts` is the Electron lifecycle (window, IPC, autosave). Putting
 * the adaptation in its own file keeps both of those true and puts the engine dependency in one
 * named place, instead of spreading it through the entry point.
 *
 * It deliberately does **not** import `electron`: it takes the app root as a parameter, so the
 * adapter is exercisable from vitest with a real `SimulationEngine` (see `tests/agent/host.test.ts`).
 *
 * Two jobs:
 *
 *  1. **Addressing.** A trigger says *what* happened, not *who* it happened to — `ship-idle` names a
 *     ship, `admiral-message` a message, `danger` nothing at all. Only the engine knows which Agent
 *     stands behind each of those, so this is where `AgentTrigger` becomes a list of `agentId`s.
 *  2. **Assembly.** Build the scheduler with a real provider when one is configured, and with a
 *     provider that always declines when one is not — which is what makes "no API key" mean
 *     *deterministic mode* rather than *no Agents*.
 */
import { SimulationEngine } from '../src/engine/engine';
import type { AgentEvent, AgentTrigger, SimulationEvent, WorldState } from '../src/engine/types';
import { MockModelClient } from './agent/mock-client';
import { loadDecisionSchema, loadPromptTemplates } from './agent/prompt';
import { AgentScheduler, type SchedulerWorld, type ScheduledAgent } from './agent/scheduler';
import type { AgentLoopStats } from '../src/engine/agent/roster';
import { createDeepSeekClient, deepSeekConfigFromEnv, describeDeepSeekConfig } from './agent/openai-compatible';
import { DecisionRuntime, type ActionSubmitter, type DecisionTrace, type MessageSubmitter } from './agent/runtime';

/** The ship an Agent commands, via the existing operator/assignment binding. */
function shipOfAgent(w: WorldState, agentId: string): string | null {
  const operator = w.operators.find((candidate) => candidate.agentId === agentId);
  return w.assignments.find((a) => a.operatorId === operator?.id)?.shipId ?? null;
}

/** The Agent commanding a ship, or `null` when the ship is run by the rules instead. */
function agentOfShip(w: WorldState, shipId: string): string | null {
  const assignment = w.assignments.find((a) => a.shipId === shipId);
  return w.operators.find((o) => o.id === assignment?.operatorId)?.agentId ?? null;
}

/** Which Agents a trigger concerns. See the module comment and plan §13.5. */
export function agentsForTrigger(w: WorldState, trigger: AgentTrigger): string[] {
  switch (trigger.kind) {
    case 'ship-idle':
    case 'directive-completed':
    case 'directive-failed': {
      const agentId = agentOfShip(w, trigger.shipId);
      return agentId === null ? [] : [agentId];
    }
    case 'admiral-message': {
      const message = w.agentMessages.find((candidate) => candidate.id === trigger.messageId);
      return message && message.to !== 'admiral' ? [message.to] : [];
    }
    case 'agent-request':
      // Both ends are named, so the recipient — who is the one that must decide — is directly known.
      return [trigger.toAgentId];
    case 'danger':
    case 'world-event':
    case 'promise-changed':
    case 'high-value-opportunity':
      // World-scoped: nothing in the payload says whose problem it is, and any Agent may care. They
      // merge into one marker each, so "broadcast" costs one decision per Agent, not one per event.
      return w.agents.map((agent) => agent.id);
    case 'no-decision-for':
      // Generated by the scheduler itself; it never travels through this path.
      return [];
  }
}

/** The engine, seen through the narrow window the scheduler is allowed. */
export function schedulerWorld(engine: SimulationEngine): SchedulerWorld {
  const w = (): WorldState => engine.state;
  return {
    time: () => w().time,
    speed: () => w().speed,
    isPaused: () => w().paused,
    isActive: () => w().status === 'active',
    agents: (): ScheduledAgent[] =>
      w().agents.map((agent) => ({ id: agent.id, nextDecisionAt: agent.nextDecisionAt })),
    agentsForTrigger: (trigger) => agentsForTrigger(w(), trigger),
    isIdle: (agentId) => {
      const shipId = shipOfAgent(w(), agentId);
      if (shipId === null) return false;
      const ship = w().ships.find((candidate) => candidate.id === shipId);
      if (!ship) return false;
      return ship.current === null && ship.queue.length === 0 && ship.suspended.length === 0;
    },
    observe: (agentId) => {
      const operator = w().operators.find((candidate) => candidate.agentId === agentId);
      return operator ? engine.getObservation(operator.id) : null;
    },
    currentDirectiveId: (agentId) => {
      const shipId = shipOfAgent(w(), agentId);
      return w().ships.find((candidate) => candidate.id === shipId)?.current?.id ?? null;
    },
    /**
     * The one thing the scheduler may write. It is a scheduling stamp rather than world state — the
     * simulation never reads it — but it lives on `Agent` because it has to persist: without it,
     * loading a save would fire every Agent on the same beat (`03-test-plan.md` `S-10`).
     */
    writeBeat: (agentId, at) => {
      const agent = w().agents.find((candidate) => candidate.id === agentId);
      if (agent) agent.nextDecisionAt = at;
    },
    log: (message, level) => engine.log(message, level),
  };
}

/**
 * The runtime's route to the engine.
 *
 * Bound through the Agent's **own** operator port, so a submitted Action is attributed to that
 * Agent rather than to the commander — the renderer's commands default to `'commander'`, and an
 * Agent must never be able to act with those powers (`KNOWN_ISSUES.md` `N-3`). This is also the
 * only module that names the engine's command seam; the agent layer never does.
 */
function submitterFor(engine: SimulationEngine): ActionSubmitter {
  return {
    submit: (action, observation) =>
      engine.controllerPort(observation.operatorId).submitAction(action),
  };
}

/**
 * The runtime's route to the world for **speech** (P3, EVT-01/02/03).
 *
 * An Agent may only speak as itself — that is precisely the `agentMessage` permission relaxation in
 * `command-system.ts` (`from === actorId && from !== 'admiral'`), so the dispatch carries the Agent's
 * own id as the actor. It is never `'commander'`: an Agent must not be able to borrow the Admiral's
 * powers, the same rule `submitterFor` above observes (`N-3`).
 */
function messengerFor(engine: SimulationEngine): MessageSubmitter {
  return {
    send: (reply, observation) =>
      engine.dispatchCommand(
        {
          type: 'agentMessage',
          from: observation.agentId,
          to: reply.to,
          kind: reply.kind,
          text: reply.text,
          payload: reply.payload,
        },
        observation.agentId,
      ),
  };
}

/** Every trigger in a frame's events. */
export function agentTriggersOf(events: readonly SimulationEvent[]): AgentTrigger[] {
  const triggers: AgentTrigger[] = [];
  for (const event of events) if (event.type === 'agentTrigger') triggers.push(event.trigger);
  return triggers;
}

/** Every settlement fact in a frame's events. */
export function agentEventsOf(events: readonly SimulationEvent[]): AgentEvent[] {
  const settled: AgentEvent[] = [];
  for (const event of events) if (event.type === 'agentEvent') settled.push(event.event);
  return settled;
}

export interface AgentHostOptions {
  /** Where `prompts/` and `schemas/` live. */
  root: string;
  /** Injected so a test can supply credentials; defaults to the real environment. */
  env?: NodeJS.ProcessEnv;
  onTrace?: (trace: DecisionTrace) => void;
}

export class AgentHost {
  private readonly engine: SimulationEngine;
  private readonly scheduler: AgentScheduler;
  /**
   * `C-36`: the loop's own tally, for the panel.
   *
   * Kept here rather than in the world on purpose — it is a property of *this run's* Agent loop (how
   * many calls, how many thrown away), not of the simulation, and putting it in `WorldState` would make
   * the save depend on network timing.
   */
  private readonly loop: AgentLoopStats = { decisions: 0, modelCalls: 0, dropped: 0, lastDrop: null };

  constructor(engine: SimulationEngine, options: AgentHostOptions) {
    this.engine = engine;
    const env = options.env ?? process.env;
    // No key configured is the normal state of a checkout, and it must not mean "no Agents": an
    // offline client that always declines gives the runtime its deterministic path, so every Agent
    // still decides — just without a model (docs/lv3/06-deepseek-runtime-status.md §5.5).
    const config = deepSeekConfigFromEnv(env);
    const client = createDeepSeekClient(env) ?? new MockModelClient({ rules: [] });
    // Say which mode this run is in, out loud, once.
    //
    // Both modes produce valid decisions and are indistinguishable from inside the game — which is
    // how a whole stage went by with the model contributing nothing while every test stayed green
    // (`KNOWN_ISSUES.md` `C-33`). A startup line is the cheapest way to make the state visible
    // instead of inferred. `describeDeepSeekConfig` reduces the key to a boolean, so this cannot leak
    // it even by accident (`02-llm-boundary.md` §7).
    //
    // **`console.error`, not `console.log`** — measured, not stylistic. On Windows the Electron main
    // process is a GUI-subsystem binary: its stdout is not delivered to the launching console, so a
    // `console.log` here is written and never seen. stderr is. Both lines below were verified by
    // launching the app and reading the terminal.
    //
    // And **not** `engine.log`: the world log lives in `WorldState`, and making persisted state depend
    // on whether the environment happens to hold an API key is precisely the environment-dependence
    // the same-seed replay assertion exists to keep out. (It would also buy nothing — `snapshot().logs`
    // is carried to the renderer but no component displays it.)
    console.error(
      config
        ? '[agent] 模型已配置 — ' + JSON.stringify(describeDeepSeekConfig(config))
        : '[agent] 未配置 DEEPSEEK_API_KEY —— 本轮为确定性模式，不调用模型',
    );
    const runtime = new DecisionRuntime({
      client,
      prompts: loadPromptTemplates(options.root),
      schema: loadDecisionSchema(options.root),
      submitter: submitterFor(engine),
      messenger: messengerFor(engine),
      // Counted here rather than taken from the scheduler: only the runtime sees the trace, and the
      // trace is where "the model answered" is distinguishable from "the deterministic rule did".
      // The caller's own hook still runs.
      onTrace: (trace) => {
        if (trace.outcome === 'provider') this.loop.modelCalls += 1;
        options.onTrace?.(trace);
      },
    });
    this.scheduler = new AgentScheduler({
      world: schedulerWorld(engine),
      runtime,
      onDecision: () => {
        this.loop.decisions += 1;
      },
      onDiscarded: (_agentId, ageTicks, limit) => {
        this.loop.dropped += 1;
        this.loop.lastDrop = { ageTicks, limit };
      },
    });
  }

  /** What the loop has done this session — `C-36`'s answer to "is the model actually being used?". */
  stats(): AgentLoopStats {
    return {
      decisions: this.loop.decisions,
      modelCalls: this.loop.modelCalls,
      dropped: this.loop.dropped,
      lastDrop: this.loop.lastDrop ? { ...this.loop.lastDrop } : null,
    };
  }

  /**
   * One host frame, after `advanceFrame`. Never throws.
   *
   * The caller must keep this out of the `advanceFrame` try/catch: a provider failure here must not
   * reach the branch that marks the world `saveBlocked` (`N-9`) — a slow model is not a broken save.
   */
  frame(events: readonly SimulationEvent[]): void {
    // Settlement runs **before** the pump, so an Agent that just finished a mission decides from the
    // state that mission left behind rather than the state before it — that ordering is what makes
    // EVT-08 lead into EVT-09 instead of being a frame late.
    for (const event of agentEventsOf(events)) {
      const result = this.engine.dispatchCommand({ type: 'agentEvent', event });
      // A refused settlement is logged, never thrown: this runs inside the host frame's own
      // try/catch, and a bad fact must not be able to stall the world (N-9).
      if (!result.ok) this.engine.log('Agent 结算被拒：' + result.reason, 'warning');
    }
    this.scheduler.notify(agentTriggersOf(events));
    this.scheduler.pump();
  }
}
